config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :sites

end

app/models/site.rb
class Site < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  def index
    @site = Site.new
    @sites = Site.all
  end

  def create
    @site = Site.create(site_params)
    if @site.save
      redirect_to sites_path
    else
      render :index
    end
  end

  def show
    @site = Site.find(params[:id])
  end

  def edit
    @site = Site.find(params[:id])
  end

  def update
    @site = Site.find(params[:id])
    @site.update_attributes!(site_params)

    redirect_to sites_path
  end

  def destroy
    @site = Site.find(params[:id]).delete

    redirect_to sites_path
  end

  private
  def site_params
    params.require(:site).permit(:site_name, :location)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCrudSites</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sites/edit.html.erb
<%= form_for @site do |f| %>
  <p>
    <%= f.label :site_name %>
    <%= f.text_field :site_name %>
  </p>
  <p>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

app/views/sites/index.html.erb
<%= form_for @site do |f| %>
  <p>
    <%= f.label :site_name %>
    <%= f.text_field :site_name %>
  </p>
  <p>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </p>
  <p>
    <%= f.submit 'Create Tourist Site' %>
  </p>
<% end %>

<% @sites.each do |site| %>
  <ul>
    <li>
      <%= link_to "#{site.site_name}", site_path(site) %>
      <br>
      <%= site.location %>
    </li>
  </ul>
<% end %>

app/views/sites/show.html.erb
<ul>
  <li>
    <%= @site.site_name %>
    <br>
    <%= @site.location %>
  </li>
</ul>

<%= link_to 'Edit', edit_site_path(@site) %>
<%= link_to 'Delete', site_path(@site), method: :delete %>

app/views/welcome/index.html.erb
<h2>Welcome</h2>

<%= link_to 'Add Tourist Site', sites_path %>